Accept Rails 7.0.0
tinfoil/devise-two-factor pull request #204
Opened 2021-12-16 13:31 UTC by kivanio

2021-12-16 16:00 UTC, bsedat commented
Thank you!

2021-12-16 17:24 UTC, bsedat commented
Looks like Rails 7.0 requires Ruby 2.7 and above.

2021-12-16 17:26 UTC, bsedat requested changes

2021-12-16 17:26 UTC, bsedat commented on .github/workflows/ci.yml
> +          - { ruby: '2.4', rails: '7.0' }
```suggestion
          - { ruby: '2.7', rails: '7.0' }
          - { ruby: '3.0', rails: '7.0' }
```

2021-12-18 14:39 UTC, andyjeffries commented
I get an error when using devise-two-factor and upgrading an app to Rails 7.0. I tried with the version from this PR and the error persists.

```
$ rails db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
rails aborted!
NoMethodError: undefined method `has_key?' for nil:NilClass
/Users/andy/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:224:in `attr_encrypted?'
/Users/andy/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/devise-two-factor-f5e97fad4dc5/lib/devise_two_factor/models/two_factor_authenticatable.rb:17:in `block in <module:TwoFactorAuthenticatable>'
```

This eventually comes from `app/models/user.rb:2` in my app which is:

```
devise :two_factor_authenticatable, :two_factor_backupable, otp_secret_encryption_key: ENV['OTP_KEY']
```

I don't know what the solution is from here, but the `attr_encrypted` latest version is 3.1.0 from 2018. I don't know if the use of that gem should be replaced with the [default Rails 7.0 solution](https://edgeguides.rubyonrails.org/active_record_encryption.html#declaration-of-encrypted-attributes) (or how we'd migrate data in existing encrypted columns to it).

2021-12-27 08:48 UTC, mitsuru commented
https://github.com/tinfoil/devise-two-factor/blob/ecd182e97e8e92436bd908af30165c18f17fe67e/lib/devise_two_factor/models/two_factor_authenticatable.rb#L10-L22

As long as `opt_secret` and` otp_secret = `are defined before loading the module,
so before trying Rails 7,I tried define `encrypts: opt_secret` provided by lockbox before the` devise: two_factor_authenticatable`.

```ruby
encrypts :otp_secret
devise :two_factor_authenticatable, ...
```

After that, I upgraded to Rails 7 with this PR and rewrite `encrypts` to `lockbox_encrypts` for Rails 7.
```ruby
lockbox_encrypts :otp_secret
devise :two_factor_authenticatable, ...
```
It worked correctly.

You need to take steps before upgrading to rails 7,
lockbox is well documented for migration from attr_encrypted.
https://github.com/ankane/lockbox#migrating-from-another-library

I propose decoupling `otp_secret` encryption from devise-two-factor and allowing Rails 7's default encrypts or lockbox to be selected.

2022-01-11 16:21 UTC, loust333 commented
Hello everyone, 

Any update concerning this issue ?

2022-01-11 16:32 UTC, andyjeffries commented
I haven't got back to upgrading that site yet due to a vacation over Xmas/NY. I'm hoping I'll have another chance this weekend and will let you know.

2022-01-11 16:37 UTC, loust333 commented
Thanks for the update @andyjeffries. 

I will try out the changes of this issue and see if there is something else that comes up. :) 

Have a nice week!

2022-01-25 00:52 UTC, jason-hobbs commented
> andyjeffries

I get this error as well after going to Rails 7.  It is the only thing keeping me from upgrading fully.  Is there any ETA for a fix or what can any of us do to help?

2022-01-25 05:21 UTC, jason-hobbs commented
I installed the lockbox gem and added the lockbox_encrypts :otp_secret
The server now starts but when I try to login I get:
NoMethodError - undefined method `otp_secret_ciphertext'

2022-01-28 06:48 UTC, jason-hobbs commented
I actually ended up using the branch from cybersecuricy here #192  and it works perfectly.

2022-01-29 18:29 UTC, andyjeffries commented
Agree, that one works perfectly for me too. Thanks @jason-hobbs

2022-02-03 22:37 UTC, burkematthew commented
Just checking in on what the next steps are here.  This is one of the gems holding me back from upgrading to Rails 7.

2022-02-04 10:27 UTC, webrails commented
I also tested @cybersecuricy's approach. Seems to work just fine after migrating `encrypted_otp_secret` to `otp_secret`.

2022-02-23 19:33 UTC, lesterkimkraken approved these changes

2022-02-23 19:35 UTC, LesterKim commented
@bsedat Does this look good to merge?

2022-02-23 19:38 UTC, merged

2022-02-23 22:28 UTC, LesterKim commented
@bsedat Thank you. Could we add a version tag as well?

2022-04-20 19:37 UTC, andyjeffries commented
I don't know about anyone else, but seeing that this was merged, I switched back to the mainline version so that I can get 4.0.1 to fix CVE-2021-43177 on Rails 7.0.2.3, but it now breaks again for me. 

If I run `rspec` in my codebase after switching, I get:

```
Failure/Error: devise :two_factor_authenticatable, :two_factor_backupable, otp_secret_encryption_key: ENV['OTP_KEY']

NoMethodError:
  undefined method `has_key?' for nil:NilClass

      encrypted_attributes.has_key?(attribute.to_sym)
                          ^^^^^^^^^
# ./app/models/user.rb:2:in `<class:User>'
# ./app/models/user.rb:1:in `<main>'
```

If I switch back to cybersecuricy's branch it works fine (but my CI run fails due to the CVE). So it looks like there's some fix on their branch that still isn't merged here.